= GradleTest Gradle Plugin
:toc:

Test your plugin against different versions of Gradle as part of your build. This plugin extends the power that the new
`GradleTestKit` brings without having to actually author code. It rather allows plugins authors to write functional tests
that looks like normal Gradle projects (multi-project is supported). This also makes it easier to create sample projects
that can directly be used in documentation.

NOTE: *If you are using a Gradle version < 2.13, it will run in legacy mode and behave like the 0.5.5 version of the plugin*.

== Previous versions of this document

* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_5/README.adoc[0.5.5]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_2/README.adoc[0.5.2]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_1/README.adoc[0.5.1]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_0/README.adoc[0.5]

== Documentation

Please visit the http://ysb33r.github.io/gradleTest[documentation website] for this plugin

== Contributions

* https://github.com/dcendents[Daniel Beland] - Gradle 2.5 fixes.
* https://github.com/szpak[Marcin Zajączkowski] - Fix for Zip errors
* https://github.com/matthiasbalke[Matthias Balke] - Documentation

If you would like to contribute fixes, please see `HACKING.adoc`.

For a list of kudos please see the http://ysb33r.github.io/gradleTest[website]

