= GradleTest Gradle Plugin
:toc:

Test your plugin against different versions of Gradle as part of your build. This plugin extends the power that the new
`GradleTestKit` brings without having to actually author code. It rather allows plugins authors to write functional tests
that looks like normal Gradle projects (multi-project is supported). This also makes it easier to create sample projects
that can directly be used in documentation.

NOTE: *If you are using a Gradle version < 2.13, it will run in legacy mode and behave like the 0.5.5 version of the plugin*.

== Previous versions of this document

* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_5/README.adoc[0.5.5]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_2/README.adoc[0.5.2]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_1/README.adoc[0.5.1]
* https://github.com/ysb33r/gradleTest/blob/RELEASE_0_5_0/README.adoc[0.5]

== Structure

.Source directory layout
----
${projectDir} / src / gradleTest /  project1  / build.gradle
                                    project2  /
                                    project3  /
----

Each directory below `gradleTest` becomes a test. Tests are executed in-folder
and expects a `build.gradle` file. If the latter is not found the test will not be
executed.

For testing, a folder is created for each gradle version to be tested and the
projects are duplicated below the verson folder. Each version testsute is executed
within a separate JVM.

.Test directory layout
----
${buildDir} / gradleTest / project1  / ver1   <1>
                                     / ver2   <2>
                         / project2  / ver1
                         / manifest  <3>
                         / src       <4>
                         / init.gradle <5>
----
<1> A folder is created for each project
<2> A folder for each Gradle version is created underneath the project folder
<3> Classpath manifest used when running tests
<4> Folder where geenrated source code ends up in
<5> Initscript used by GradleTest

.Test layout for one test
----
... / project1 / .gradle         <1>
               / build           <2>
               / build.gradle    <3>
               / settings.gradle <4>
----
<1> Project cachedir is sent here
<2> It is recommended that the build directory not be changed and left as per default
<3> `build.gradle` is required for the test to be executed. It must contain a task called `runGradleTest`.
<4> If a test project does not have a `settings.gradle file` an empty one will
be generated in the test folder

== Bootstrap

GradleTest is available in the https://plugins.gradle.org/plugin/org.ysb33r.gradletest[Gradle Plugins] repository.
To use it, add the following snippet into your build script.

[source,groovy]
----
plugins {
  id 'org.ysb33r.gradletest' version '1.0'
}
----

When your setup is more complex and the plugins block does not work OR if you are using Gradle 2.0 use the following instead

[source,groovy]
----
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"         // <1>
    }
  }

  dependencies {
    classpath 'org.ysb33r.gradle:gradletest:0.5.4' // <2>
  }
}

apply plugin: 'org.ysb33r.gradletest'             // <3>
----
<1> Add the Gradle Plugins repository.
<2> Add the last version as a buildscript dependency.
<3> Apply the plugin.

== Task Configuration

[source,groovy]
----
gradleTest {
  versions '2.2','2.4-beta1'   // <1>

  initscript '/path/to/script' // <2>

}
----
<1> Test against the listed versions
<2> All gradle tests are invoked with a default initscript. This
  can be changed by setting your own init script. This path is evaluated
  with `project.file`.

== Overriding Gradle Distribution Location

With the 1.0 release the location for distributions are determined by `GradleTestKit`. However it is possible to
override that and set a base location to find distributions by two possible means.

.Configure distribution location by task
[source,groovy]
----
gradleTest {
  distributionUri 'file://local/area' // <1>
}
----
<1> Set local area to find Gradle distributions instead of default Gradle location. When this is set Gradle will only look
  here for distributions.

.Configure distribution location by system property
----
-Dorg.ysb33r.gradletest.distribution.uri=file://local/area
----

NOTE: When the system property is set it will override all `distributionUri` settings in task configurations

== Start Parameters

* If gradle is run with `--offline`, it will be passed to the Gradle.
* `--project-cache-dir` is always set to at the start of the project in `buildDir`
* `--full-stacktrace` is set and output is captured to test report.

== Temporarily overriding Gradle versions

It is very convenient to sometimes to runs the test with a subset of the versions specified in the configuration. This is
achievable by passing a system property to Gradle

[source,bash]
----
-DgradleTest.versions=2.2,2.3 <1> <2>
----
<1> If more than one GradleTest task is defined, replace `gradleTest` with the name of the appropriate GradleTest task.
<2> List the versions in a commma-separated list. No validation is done on the string. If it leads to invalid Gradle
  versions the build will fail.

== Task dependencies

`gradleTest` is now linked into the `check` lifecycle task.

== Dependencies

Although gradle tests can download their own dependencies, this might consume unnecessary
bandwidth and waste a lot of testing time. In order to combat this,
any dependencies listed under `gradleTest` configuration will be downloaded and
made available to the running gradle tests.

.Define dependencies in build.gradle
[source,groovy]
----
dependencies {
  gradleTest 'commons-cli:commons-cli:1.2'
}
----

These dependencies then appear as a `flatDir` repository in the gradle test.

*NOTE*: It is not necessary to add your plugin to the dependencies. The output of the `jar` task
is automatically added to the `gradleTest` configuration.

.Configure test build.gradle for dependency
[source,groovy]
----
buildscript {
  dependencies {
    classpath ':gnumake:1.0.1' // <1>
  }
}

dependencies {
  compile ':commons-cli:1.2' // <2>
}
----
<1> It is completely possible to add it to the `buildscript` for loading
  plugins
<2> Load up any dependencies a per normal


*NOTE*:This repository is injected into the test using the default initscript. If you use your own `initscript`
and still want to avail your own feature you'll need to add the following to your `initscript`.

[source,groovy]
----
buildscript {
  repositories {
    flatDir {
      dirs
    }
  }
}

allprojects {
  repositories {
  }
}
----

== Adding additional GradleTest tasks

It is possible to add additional test tasks beyond `gradleTest`, by doing

[source,groovy]
----
configurations {
  furtherTest
}

task furtherTest( type : org.ysb33r.gradle.gradletest.legacy20.GradleTest ) {
  versions '2.2'
}
----

Test files should be placed under `src/furtherTest` using the same layout as described earlier. Dependencies should be
listed under `furtherTest` configuration.

Global configuration is still read from `gradleLocations` project extension.

== Dynamic dependencies

Hard-coding the plugin version in to the `build.gradle` files of the `gradleTest` test fixtures is a maintenance pain.
However the plugin is injected automatically into the build via `GradleTestKit`.

== Awesomeness

This plugin is so awesome, it applies to itself and then runs a collection of tests - See `gradle/self-reference.gradle`
on how this is done.

== Known Limitations

* Not designed to work Gradle < 2.0. If the community requires this functionality an effort will be made to see if it is
  possible. (It will actually try to runs tests against a Gradle version < 2.0, if configured in `gradleTest`)
* Does not run test in parallel, even though it theoretically could. Can do with a `maxParallelForks`. (https://github.com/ysb33r/gradleTest/issues/5)
* Runs in legacy mode when the project is built with Gradle 2.0 - 2.12.

== Advanced Features (Gradle 2.13+)

=== Overriding dependencies

GradleTest uses Spock Framework, JUnit & Apache Commons IO underneath. If, for some reason you need to override the
versions of these dependencies it can be done in the `gradleTestCompile` configuration. If you created a new `GradleTest`
task called `foobar` then the appropriate configuration will be callled `foobarCompile`.


== Legacy mode (Gradle 2.0-2.12)

If you are building your plugin project with any Gradle version 2.0 - 2.12 it automatically invoked legacy mode and
behaves like the v0.5.5 version of this plugin.

=== Global Configuration

[source,groovy]
----
gradleLocations {
  searchGradleUserHome = true      // <1>
  includeGradleHome = true         // <2>
  searchGvm = true                 // <3>
  download = true                  // <4>
  downloadToGradleUserHome = false // <5>
  useGradleSite = true             // <6>
  uri                              // <7>
  search                           // <8>
}
----
<1> Search Gradle home for Gradle installations.
<2> Include the current `GRADLE_HOME` folder.
<3> Search the GVM folder for Gradle installations
<4> Download uninstalled version if online. These distributions will be
  placed in the appropriate location in `gradle.gradleHome`.
<5> Place downloaded distributions in `gradle.gradleUserHomeDir` in the same way
  Gradle wrapper will do.
<6> Download distribution from the global Gradle distribution site.
<7> List additional URLs to search for Gradle distributions.
<8> Search these additional folders for Gradle installations. Search will be performed
    both as if it a cache-style folder (aka `gradleUserHome`) or an installation-style folder
    (aka `GVM_HOME`).

NOTE: If the above is used with Gradle 2.13+ it will be accepted and ignored. Deprecation warnings will also be printed.

=== Dynamic dependencies

Hard-coding the plugin version in to the `build.gradle` files of the `gradleTest` test fixtures is a maintenance pain.
In previous versions of the plugin one had to dp to write something like

[source,groovy]
----
buildscript {
  dependencies {
    classpath ':gnumake:%%VERSION%%'
  }
}
----

and the plugin would substitute the `%%VERSION%%` token with the version of your project. This is *no longer necessary
with this release* even when running in legacy mode. The plugin will inject the path to the plugin automatically
eliminating the need to use a block like the above at all.

=== Task dependencies

The `gradleTest` task is not linked to any other tasks. Run this as
explicit task on the command-line or add your own task dependencies in your
gradle script. The reason for this is that  in legacy mode it can be quite a time-consuming testset to run. The typical
case will be that the tests are only run close to release time. If you prefer you might want to set
`install.dependsOn gradleTest` rather than `check.dependsOn gradleTest` or `build.dependsOn gradleTest`.

=== Test directory layout

For testing, a folder is created for each gradle version to be tested and the
projects are duplicated below the verson folder. Each version's testsuite is executed
within a separate JVM.

.Test directory layout
----
${buildDir} / gradleTest / ver1 / project1 <1>
                                / project2
                                / project3
                         / ver2 / project1
                                / project2
                                / project3
                         / init20.gradle   <2>
                         / repo            <3>
                         / home            <4>
            / classes / gradleTest         <5>
            / gradleDist                   <6>
----
<1> Projects are duplicated for each Gradle version. See below for a more detailed
  layout
<2> This is a generated `initscript` used to start all tests.
<3> This is flat repository that can be utilised by all tests.
<4> Gradle home directory for all the tests
<5> Temporary classes for bootstrapping the tests are kept here.
<6> Distributions are downloaded here if necessary

.Test layout for one test
----
... / project1 / .gradle         <1>
               / src             <2>
               / build           <3>
               / build.gradle    <4>
               / settings.gradle <5>
----
<1> Project cachedir is sent here
<2> If the test project has any folders they will be copied here
<3> It is recommended that the build directory not be changed and left as per default
<4> `build.gradle` is required for the test to be executed. It must contain a task called `runGradleTest`.
<5> If a test project does not have a `settings.gradle file` an empty one will
be generated in the test folder

=== Known Limitations

* The plugin assumes that no Gradle distributions in `gradle,gradleUserHomeDir` or `GVM_HOME` will be removed whilst it
  is running.
* The source sets for the Gradle tests cannot be renamed or added to. The subdirectory name is fixed to the task name.
* No nice HTML report (https://github.com/ysb33r/gradleTest/issues/2)
* No graceful failure as for `test` task. Currently throws a `TaskExecutionException` at the end, which is ugly. (https://github.com/ysb33r/gradleTest/issues/1)
* No running counter of tests run and test failures (as for `test` task). (https://github.com/ysb33r/gradleTest/issues/3)
* All test output is going to stdout instead of being captured and added to test report. (https://github.com/ysb33r/gradleTest/issues/4)
* `--no-daemon` is set, as we don't want to clash with existing running daemons.


== Contributors

* https://github.com/dcendents[Daniel Beland] - Gradle 2.5 fixes.
* https://github.com/szpak[Marcin Zajączkowski] - Fix for Zip errors
* https://github.com/matthiasbalke[Matthias Balke] - Documentation

If you would like to contribute fixes, please see `HACKING.adoc`

