== Beyond the Basics

=== Base plugin

If the convention of adding a `gradleTest` with it's default settings are not suitable for your
environment, then the base plugin can be considered. This will only add the
`additionalGradleTestSet` method.
The GradleTest Base Plugin is available in the https://plugins.gradle.org/plugin/org.ysb33r.gradletest.base[Gradle Plugins] repository.
To use it, add the following snippet into your build script.

[source,groovy,subs="attributes"]
----
plugins {
  id 'org.ysb33r.gradletest.base' version '{revnumber}'
}
----

When your setup is more complex and the plugins block does not work use the following instead

[source,groovy,subs="attributes"]
----
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }

  dependencies {
    classpath 'org.ysb33r.gradle:gradletest:{revnumber}'
  }
}

apply plugin: 'org.ysb33r.gradletest.base'
----

=== Add additional compatibility test sets

Use the `additionalGradleTestSet` project extension. Specify the basename and all of
the appropriate configurations and tasks will be added.

[source,groovy]
----
include::{compatdir}/compatibility.gradle[tags=addTestSets]
----
<1> Supply basename to `additionalGradleTestSet`
<2> This will result in a test task in the format `${baseName}GradleTest`. Sources are expected to be layed out below
  the `src/${baseName}GradleTest` folder in a similar fashion to `gradleTest`
<3> Configure test task as per normal.
<4> Other tasks in the groups are all named using the same convention and can also
  just be configured as per normal.

=== Provide more feedback during test execution

Running lots of compatibility tests can take some time. If you need more visual feedback
regarding progress try adding something like this to the `gradleTest` configuration.

[source,groovy]
----
gradleTest{
  beforeTest {
    println "  ${it.name}" // <1>
  }
}
----
<1> Print the name of the current compatibility test that is runnign

=== Kotlin DSL

With the growing use of Kotlin-based build scripts, it is also important to test compatibility of a plugin for this context. Turn Kotlin-testing on by setting the following:

[source,groovy]
----
gradleTest {
  kotlinDsl = true
}
----

Now drop a `build.gradle.kts` file alongside your `build.gradle` build script. If the Gradle version under test is 4.0 or later, GradleTest will also run a test using the Kotlin build script.


