== Command-line Awareness

=== Gradle standard options

GradleTest is aware of certain command-line parameters and will pass them on to running tests.

* `--rerun-tasks` - All tests will be re-run even if they were previsouly successful.
* `--offline` - No dependency checks will be performed and if plugins implements any offline behaviour this will automatically be enabled.

=== Temporarily overriding Gradle versions

It is very convenient to sometimes to runs the test with a subset of the versions specified in the configuration. This is
achievable by passing a system property to Gradle

[source,bash]
----
-DgradleTest.versions=3.5,4.4.1 <1> <2>
----
<1> If more than one GradleTest task is defined, replace `gradleTest` with the name of the appropriate GradleTest task.
<2> List the versions in a commma-separated list. No validation is done on the string. If it leads to invalid Gradle
  versions the build will fail.

=== Selecting what tests to run

There are 2 ways to select what tests GradleTest will run, but there is little bit of background needed.
First, understand that GradleTest is a code generator with the ability to run the generated code.  For
each build file in your `src/gradleTest/{name}` folder, there is an associated Spock test class generated in
the background.  Those generated files can be found in the `${buildDir}/gradleTest/src/groovy` folder.
The content of those files are not important at the moment, but the file names are as that is what you will use to specify
specifically what tests to run.

So take this folder structure:

[source,bash]
----
src/gradleTest/mytest
    build.gradle
src/gradleTest/theirtest
    build.gradle
----

That gets fed thru the test generator code and generates this folder structure

[source,bash]
----
${buildDir}/gradleTest/src/groovy
    Mytest_BuildGroovyDSLCompatibilitySpec.groovy
    Theirtest_BuildGroovyDSLCompatibilitySpec.groovy
----

It is the resulting files that you use to filter what tests you want to run.  The first
way is to specify a single specific file

[source,bash]
----
-DgradleTest.single=Mytest_BuildGroovyDSLCompatibilitySpec
----

That will run that one and only that one test

The second technique is to use an Ant file pattern, or more commonly referred as a glob.  Examples
of how to write globs can be found here:

https://ant.apache.org/manual/Types/patternset.html

GradleTest allows you to specify either include globs or exclude globs, similar to Ant, using
the following properties.

[source,bash]
----
-PgradleTest.glob.include=*Build*.*
----

[source,bash]
----
-PgradleTest.glob.exclude=Their*
----

These properties can be put into a `gradle.properties` or passed in as command line parameters like above.

Some notes about globs

* globs are case sensitive.
* For both include and exclude, you can specify multiple globs by delimiting them with a semicolon

[source,bash]
----
-PgradleTest.glob.exclude=*Build*.*;Their*
----

* the filter starts at the  `${buildDir}/gradleTest/src/groovy` folder so the preceding "**/" is not necessary
