== Task Configuration

=== Gradle versions to test against

[source,groovy]
----
gradleTest {
  versions '2.2','2.4-beta1'   // <1>
}
----
<1> Test against the listed versions. (`versions` can be called more than once and additional listings will
  just be appended).

=== Marking test builds for failure

It is possible to mark specific tests (build scripts) to be expected failures. 
This is useful for cases where negative testing such as missing flags etc. need to be performed.
(This is effectively TestKit's `buildAndFail` at a larger scale)*[]:

[source,groovy]
----
gradleTest {
    expectFailure ~/foo/ // <1>
    expectFailure 'bar' // <2>
}
----
<1> All test names matching this regular expression (`Pattern`) will be marked as expected failures.
  The test names reflect the folder name below `gradleTest`.
<2> Similar as before, but using a string alternative.

=== Overriding Gradle Distribution Location

With the 1.0 release the location for distributions are determined by `GradleTestKit`. However it is possible to
override that and set a base location to find distributions by two possible means.

.Configure distribution location by task
[source,groovy]
----
gradleTest {
  distributionUri 'file://local/area' // <1>
}
----
<1> Set local area to find Gradle distributions instead of default Gradle location. When this is set Gradle will only look
  here for distributions.

.Configure distribution location by system property
----
-Dorg.ysb33r.gradletest.distribution.uri=file://local/area
----

NOTE: When the system property is set it will override all `distributionUri` settings in task configurations

=== Setting new Distribution Filename Pattern

Some corporations repackage custom distributions of Gradle for inside their corporations.  With these
distributions, its common to brand them with a different filename.  GradleTest is capable of pulling these
distributions as well.

[source,groovy]
----
gradleTest {
    distributionUri 'https://mycompany.com/dist/gradle' // <1>
    gradleDistributionFilenamePattern "mycompany_gradle-@version@-bin.zip"
}
----

If you do not set the `distributionUri` along with the filename pattern, GradleTest will attempt to download
your corporate release from the primary Gradle site, resulting in an error.

The `@version@` of the above filename is a replacement token.  When GradleTest is run, it will replace
this token with the requested gradle version.

=== Start Parameters

* If gradle is run with `--offline`, it will be passed to the Gradle.
* `--full-stacktrace` is set and output is captured to test report.

=== Deprecation Messages

As Gradle evolves, certain functionality is marked as deprecated. When these messages are detected during testing, it will
cause the compatibility test to fail. This behaviour can be turned on (default) or off via the `deprecatedMessagesAreFailures` setting.

[source,groovy]
----
gradleTest {
  deprecatedMessagesAreFailures false // <1>
}
----
<1> Turns off default behaviour of failing on deprecated Gradle functionality.
