= Legacy Mode (Gradle 2.0-2.12)

If you are building your plugin project with any Gradle version 2.0 - 2.12 it automatically invoked legacy mode and
behaves like the v0.5.5 version of this plugin.

== Global Configuration

[source,groovy]
----
gradleLocations {
  searchGradleUserHome = true      // <1>
  includeGradleHome = true         // <2>
  searchGvm = true                 // <3>
  download = true                  // <4>
  downloadToGradleUserHome = false // <5>
  useGradleSite = true             // <6>
  uri                              // <7>
  search                           // <8>
}
----
<1> Search Gradle home for Gradle installations.
<2> Include the current `GRADLE_HOME` folder.
<3> Search the GVM folder for Gradle installations
<4> Download uninstalled version if online. These distributions will be
  placed in the appropriate location in `gradle.gradleHome`.
<5> Place downloaded distributions in `gradle.gradleUserHomeDir` in the same way
  Gradle wrapper will do.
<6> Download distribution from the global Gradle distribution site.
<7> List additional URLs to search for Gradle distributions.
<8> Search these additional folders for Gradle installations. Search will be performed
    both as if it a cache-style folder (aka `gradleUserHome`) or an installation-style folder
    (aka `GVM_HOME`).

NOTE: If the above is used with Gradle 2.13+ it will be accepted and ignored. Deprecation warnings will also be printed.

== Dynamic dependencies

Hard-coding the plugin version in to the `build.gradle` files of the `gradleTest` test fixtures is a maintenance pain.
In previous versions of the plugin one had to dp to write something like

[source,groovy]
----
buildscript {
  dependencies {
    classpath ':gnumake:%%VERSION%%'
  }
}
----

and the plugin would substitute the `%%VERSION%%` token with the version of your project. This is *no longer necessary
with this release* even when running in legacy mode. The plugin will inject the path to the plugin automatically
eliminating the need to use a block like the above at all.

== Task dependencies

The `gradleTest` task is not linked to any other tasks. Run this as
explicit task on the command-line or add your own task dependencies in your
gradle script. The reason for this is that  in legacy mode it can be quite a time-consuming testset to run. The typical
case will be that the tests are only run close to release time. If you prefer you might want to set
`install.dependsOn gradleTest` rather than `check.dependsOn gradleTest` or `build.dependsOn gradleTest`.

== Test directory layout

For testing, a folder is created for each gradle version to be tested and the
projects are duplicated below the verson folder. Each version's testsuite is executed
within a separate JVM.

.Test directory layout
----
${buildDir} / gradleTest / ver1 / project1 <1>
                                / project2
                                / project3
                         / ver2 / project1
                                / project2
                                / project3
                         / init20.gradle   <2>
                         / repo            <3>
                         / home            <4>
            / classes / gradleTest         <5>
            / gradleDist                   <6>
----
<1> Projects are duplicated for each Gradle version. See below for a more detailed
  layout
<2> This is a generated `initscript` used to start all tests.
<3> This is flat repository that can be utilised by all tests.
<4> Gradle home directory for all the tests
<5> Temporary classes for bootstrapping the tests are kept here.
<6> Distributions are downloaded here if necessary

.Test layout for one test
----
... / project1 / .gradle         <1>
               / src             <2>
               / build           <3>
               / build.gradle    <4>
               / settings.gradle <5>
----
<1> Project cachedir is sent here
<2> If the test project has any folders they will be copied here
<3> It is recommended that the build directory not be changed and left as per default
<4> `build.gradle` is required for the test to be executed. It must contain a task called `runGradleTest`.
<5> If a test project does not have a `settings.gradle file` an empty one will
be generated in the test folder

== Known Limitations

* The plugin assumes that no Gradle distributions in `gradle,gradleUserHomeDir` or `GVM_HOME` will be removed whilst it
  is running.
* The source sets for the Gradle tests cannot be renamed or added to. The subdirectory name is fixed to the task name.
* No nice HTML report (https://github.com/ysb33r/gradleTest/issues/2)
* No graceful failure as for `test` task. Currently throws a `TaskExecutionException` at the end, which is ugly. (https://github.com/ysb33r/gradleTest/issues/1)
* No running counter of tests run and test failures (as for `test` task). (https://github.com/ysb33r/gradleTest/issues/3)
* All test output is going to stdout instead of being captured and added to test report. (https://github.com/ysb33r/gradleTest/issues/4)
* `--no-daemon` is set, as we don't want to clash with existing running daemons.
* Init scripts can no longer be passed. (This will probably be addressed in another release).
* Does not run test in parallel, even though it theoretically could
