= Testkit Mode (Gradle 2.13+)

== Getting Started

In `build.gradle` define the versions of Gradle that needs to be tested:

[source,groovy]
----
gradleTest {
   versions '2.9', '3.4', '4.1'
}
----

Create a folder called `src/gradleTest`. Beneath that add a folder - call it 'myExample` for now. Within that create a normal Gradle project i.e. drop a `build.gradle` file and fill it out with the kind of syntax that a person will use to run your plugin. Finally add a custom task called `runGradleTest` and make it depend on some task that your plugin provides.

For example here is one example from GradleTest's test suite of how itself is being tested.

[source,groovy]
----
include::{compatdir}/src/nonLegacyOnlyGradleTest/negativeTest/build.gradle[]
----

== Conventions

=== Filesystem

.Source directory layout
----
${projectDir} / src / gradleTest /  project1  / build.gradle
                                              / testTwo.gradle
                                    project2  /
                                    project3  /
----

Each directory below `gradleTest` becomes a test. Tests are executed in-folder.  The
test folder can have more than one build file in it.  Each build file will be considered
an individual test that is executed independently of the others.

With multiple build files, its important to remember that GradleTest will reuse the existing
`${buildDir}`.  So in the example above, if `build.gradle` happens to be executed first, then when
`testTwo.gradle` is executed, it will reuse the build folder that was created by `build.gradle`.

If this is not desired, then add the `clean` task to all your build execution scripts like this:

.Cleaning before multi-test
----
apply plugin : 'my.project.id'

task runGradleTest {
  dependsOn 'clean', 'someTask'
}
----

For testing, a folder is created for each gradle version to be tested and the
projects are duplicated below the verson folder. Each version testsute is executed
within a separate JVM.



.Test directory layout
----
${buildDir} / gradleTest / project1  / ver1   <1>
                                     / ver2   <2>
                         / project2  / ver1
                         / manifest  <3>
                         / src       <4>
                         / init.gradle <5>
----
<1> A folder is created for each project
<2> A folder for each Gradle version is created underneath the project folder
<3> Classpath manifest used when running tests
<4> Folder where generated source code ends up in
<5> Initscript used by GradleTest

.Test layout for one test
----
... / project1 / .gradle         <1>
               / build           <2>
               / build.gradle    <3>
               / settings.gradle <4>
----
<1> Project cachedir is sent here
<2> It is recommended that the build directory not be changed and left as per default
<3> `build.gradle` is required for the test to be executed. It must contain a task called `runGradleTest`.
<4> If a test project does not have a `settings.gradle file` an empty one will
be generated in the test folder

.Setting up your test project's build.gradle
----
apply plugin : 'my.project.id'   <1>

task runGradleTest {
  dependsOn 'someTask'   <2>
}
----
<1> Use `apply plugin` instead as it works across a larger range of Gradle versions. (No need for `buildscript` block
  as GradleTest will take care of injecting the plugin on the classpath).
<2> Create a `runGradleTest` task and make it depend on the real task from your plugin that needs execution.

=== Gradle Entities

A `GradleTest` task called `gradleTest` will have the following associated entities:

[cols="3*",options="header"]
|===
|Entity
|Type
|Description

| `gradleTest`
| Configuration
| For local available dependencies.

| `gradleTest`
| Task
| The actual `GradleTest` task type (extending `Test` task type).

| `gradleTest`
| SourceSet
| Manages internal generated source code

| `gradleTestCompile`
| Configuration
| Internal configuration for dependencies required to compile compatibility tests.

| `gradleTestRuntime`
| Configuration
| Internal configuration for dependencies required execute tests (different classpath to those passed to
  actual `GradleRunner` invocation).

| `gradleTestGenerator`
| Task
| Generates test code that will be compiled and used to actually executed `GradleTestKit`-based code

| `compileGradleTestGroovy`
| Task
| Compiles Groovy code generated by `gradleTestGenerator`

| `gradleTestClasses`
| Task
| Associated `classes` task for `compileGradleTestGroovy`

| `gradleTestClasspathManifest`
| Task
| Creates a classpath manifest file that will be used during test execution to load the correct plugin and
  transitive dependencies

|===
