
== Temporarily overriding Gradle versions

It is very convenient to sometimes to runs the test with a subset of the versions specified in the configuration. This is
achievable by passing a system property to Gradle

[source,bash]
----
-DgradleTest.versions=2.2,2.3 <1> <2>
----
<1> If more than one GradleTest task is defined, replace `gradleTest` with the name of the appropriate GradleTest task.
<2> List the versions in a commma-separated list. No validation is done on the string. If it leads to invalid Gradle
  versions the build will fail.

== Task dependencies

`gradleTest` is linked into the `check` lifecycle task.

== HTML Reports

HTML reports will appear as folder named after the `GradleTest` instance below the `${reporting.baseDir}` folder.
 Practically in most cases this will be `build/reports/gradleTest`.

== Add additional compatibility test sets

Use the `additionalGradleTestSet` project extension. Specify the basename and all of
the appropriate configurations and tasks will be added.

[source,groovy]
----
include::{compatdir}/compatibility.gradle[tags=addTestSets]
----
<1> Supply basename to `additionalGradleTestSet`
<2> This will result in a test task in the format `${baseName}GradleTest`. Sources are expected to be layed out below
  the `src/${baseName}GradleTest` folder in a similar fashion to `gradleTest`
<3> Configure test task as per normal.
<4> Other tasks in the groups are all named using the same convention and can also
  just be configured as per normal.

== More feedback

Running lots of compatibility tests can take some time. If you need more visual feedback
regarding progress try adding something like this to the `gradleTest` configuration.

[source,groovy]
----
gradleTest{
  beforeTest {
    println "  ${it.name}" // <1>
  }
}
----
<1> Print the name of the current compatibility test that is runnign


